# Generated by Django 5.1.2 on 2024-10-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('edad', models.DateTimeField()),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
